Post http://localhost:3001/emails
content-type: application/json

{"name":"RMC","email":"mresnicoff@gmail.com", "subject":"mentorias","message":"Hola Chicos como les va"}


###
POST http://localhost:3001/asignarPermisos
content-type: application/json

{"Hola":"hola"}
###
GET http://localhost:3001/getdatos?zona=General%20Paz